Repository moogahman/kiowsky-app, pull requests merged in 2024-06, with the labels that each got.

#3 Add env
  .env.vault
  .gitignore
  package.json
  src/env.ts
Labels: upkeep

#9 Replace jest with vitest
  __tests__/firebaseConfig.test.ts
  jest.config.mjs
  package.json
  pnpm-lock.yaml
  tsconfig.json
  vitest.config.ts
Labels: feature

#11 Fix TSC build
  package.json
  tsconfig-build.json
Labels: bug

#7 Add env types
  __tests__/firebaseConfig.test.ts
  package.json
  src/env.ts
  src/firebaseConfig.ts
  src/index.ts
  vitest.config.ts
Labels: refactor
